### ISSUE TITLE
Move build system information to pyproject.toml

### ISSUE THREAD

**Issue by vnadhan** [dgoeries/lttbc#20]
Hi @dgoeries 

The latest pip version (23.0.1) removed the capability to build python packages that use a `setup.py` file. Moving the build information to `pyproject.toml` will enable an user to build the `lttbc` package on any environment, including OSX systems. 

Do you allow contributions for this package?

**Comment by dgoeries** [comment]
thanks for the feedback, will follow up quickly.

**Comment by vnadhan** [comment]
Thanks @dgoeries for the quick fix!
